services:
  app:
    build:
      context: ./node
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace:cached
    ports:
      - "14000:14000"
      - "14001:14001"
      - "6006:6006"
    command: sleep infinity
